name: Lint, test and deployment pipeline
permissions:
  contents: write
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  basic_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check styling
        run: npm run lint
      - name: Testing
        run: npm run test

      - name: Deploy to render
        if: ${{ github.event_name == 'push' }}
        uses: JorgeLNJunior/render-deploy@v1.4.7
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true
          wait_deploy: true
          deployment_environment: "production"
